print("Welcome to Dex Shop")
print("-------------------")
print("Orange", 3, 30, "THB", 3*30.0, "THB")
print("Banana", 1, 10, "THB", 1*10.0, "THB")
print("Mango", 5, 20, "THB", 5*20.0, "THB")
print("Kiwi", 7, 15, "THB", 7*15.0, "THB")
print("Papaya", 1, 40, "THB", 1*40.0, "THB")
print("-------------------")
print("Total", "....", "THB")
print("Thank You : Dex Shop")